version: "3"

networks:
  music-editor:

services: 
  api:
    container_name: api
    build: ./api
    command: npm run start 
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - api/.env
    restart: always
    networks:
      - music-editor
  www:
    container_name: www
    build: 
      context: ./www
    command: npm run client
    ports: 
      - "8080:8080"
    depends_on:
      - api
    restart: always
    networks:
      - music-editor
  postgres:
    container_name: postgres
    build: 
      context: ./postgres
    image: postgres:9.6.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - api/.env
    restart: always
    networks:
      - music-editor
