version: "3"

services: 
  web:
    container_name: music-editor
    build: .
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
  postgres:
    container_name: postgres
    image: postgres:9.6.2-alpine
    ports:
      - "5432:5432"
    volumes:
      - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always
