version: "3"

networks:
  music-editor:

services: 
  app:
    container_name: app
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    env_file:
      - .env
    restart: always
    networks:
      - music-editor
  postgres:
    container_name: postgres
    build: 
      context: ./postgres
    image: postgres:9.6.2-alpine
    ports:
      - 5432:5432
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    restart: always
    networks:
      - music-editor
